name: Tests

on:
  # if pushed directly to the master
  push:
    branches:
      - master
      - release/*
      - ci/*
  # on a pull request
  pull_request:
    branches:
      - master
      - release/*
      - ci/*

jobs:
  # runs unit tests with default config, submits the coverage report
  unit-test:
    name: Default Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@0f62d2ad8407a414cddd4790bed06fd9ebda0f56 # v1
        with:
          java-version: 11

      - name: Check
        uses: eskatos/gradle-command-action@b3afdc78a7849557ab26e243ccf07548086da025 # v1
        with:
          arguments: check

      - name: Build Coverage Report
        uses: eskatos/gradle-command-action@b3afdc78a7849557ab26e243ccf07548086da025 # v1
        with:
          arguments: coverageReport

      - name: Upload Coverage Report
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192 # v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml

  # Make sure it works with all standard JVMs on main OSes
  platform-test:
    name: Java ${{ matrix.java }}
    continue-on-error: ${{ matrix.java != '11' && matrix.java != '8' }}
    strategy:
      matrix:
        java: [ "8", "11", "12", "13", "14", "15", "16", "17" ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@0f62d2ad8407a414cddd4790bed06fd9ebda0f56 # v1
        with:
          java-version: ${{ matrix.java }}

      - name: Check
        uses: eskatos/gradle-command-action@b3afdc78a7849557ab26e243ccf07548086da025 # v1
        with:
          arguments: check